# Generated by Django 5.0.2 on 2024-07-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=255)),
                ('continent_code', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=255)),
                ('plus_code', models.CharField(max_length=20)),
                ('principal_subdivision', models.CharField(max_length=255)),
                ('principal_subdivision_code', models.CharField(max_length=10)),
                ('administrative', models.JSONField()),
                ('informative', models.JSONField()),
            ],
        ),
    ]
