# Generated by Django 5.0.7 on 2024-07-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='informative',
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(default='sauti_salama_03e11b43', max_length=255, primary_key=True, serialize=False),
        ),
    ]
