# Generated by Django 5.0.2 on 2024-07-31 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supportservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.report')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supportservice')),
            ],
        ),
    ]
