# Generated by Django 5.0.2 on 2024-08-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_ngoprofile_professionalprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='tokens',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='availability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='profession',
            field=models.CharField(max_length=100),
        ),
    ]
